### ISSUE TITLE
Run master each night

### ISSUE THREAD

**Issue by xhochy** [JDASoftwareGroup/kartothek#18]
We should run master tests each night (easily configurable in the Travis UI) and get also notifications for all maintainers about the failures. Normally Travis will only notify the committers of the last commit.

**Comment by fjetter** [comment]
I've added a _run master daily_ cron job. Letting them _nightly_ is not an option but I believe that's not a big deal.

Concerning build notifications we can set up something [like](https://docs.travis-ci.com/user/notifications/#configuring-email-notifications):
```
notifications:
  email:
    recipients:
      - one@example.com
      - other@example.com
```
I.e. everybody who wants to get notified needs to provide an email address. This is probably something everyone may do on his/her own.
